url: 'http://0.0.0.0:8082'

mongodb:
  server:   'MONGODB_HOST_PORT'
  database: 'MONGODB_DATABASE'
  user:     'MONGODB_USER'
  password: 'MONGODB_PASSWORD'
  connectionString:       # alternative to setting server, database, user and password separately

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api' # must be accessible without a proxy
  pollingInterval:        10000      # ten seconds
  timeout:                5000       # five seconds
  userAgent:              NodeUptime/3.0 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         60000      # one minute
  qosAggregationInterval: 600000     # ten minutes
  pingHistory:            8035200000 # three months

autoStartMonitor: true

plugins:
  - ./plugins/console
  - ./plugins/patternMatcher
  - ./plugins/httpOptions
  MORE_PLUGINS
  # - ./plugins/email
  # - ./plugins/basicAuth

email:
  method:      SMTP  # possible methods are SMTP, SES, or Sendmail
  transport:         # see https://github.com/andris9/nodemailer for transport options
    service:   'EMAIL_SERVICE'
    auth:            
      user:    'EMAIL_USER'
      pass:    'EMAIL_PASSWORD'
  event:
    up:        true
    down:      true
    paused:    false
    restarted: false
  message:           
    from:      'EMAIL_FROM'
    to:        'EMAIL_TO'
  # The email plugin also uses the main `url` param for hyperlinks in the sent emails

basicAuth:
  username:    'AUTH_USERNAME'
  password:    'AUTH_PASSWORD'
verbose: DEBUG # only used in dev

webPageTest:
  server: 'http://www.webpagetest.org'
  key:
  testOptions: 


